@extends('layouts.master')

@section('content')
<main class="min-h-screen bg-slate-50 py-12">
    <div class="mx-auto max-w-6xl px-4">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-black uppercase tracking-wider text-emerald-600">My Card</p><h1 class="mt-2 text-3xl font-black text-slate-950">আমার ভার্চুয়াল কার্ড</h1><p class="mt-2 text-slate-500">Admin approve করা card information এখানে দেখতে পারবেন।</p></div><a href="{{ route('orders.index') }}" class="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-slate-700">আমার অর্ডার</a></div>
        @if($cards->isEmpty())<div class="mt-8 rounded-3xl bg-white p-12 text-center shadow-xl"><div class="text-4xl">▣</div><h2 class="mt-4 text-xl font-black text-slate-900">এখনও কোনো approved card নেই</h2><p class="mt-2 text-slate-500">Order approve হলে card information এখানে দেখা যাবে।</p><a href="{{ url('/') }}#order" class="mt-6 inline-block rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white">কার্ড কিনুন</a></div>@else<div class="mt-8 grid gap-6 md:grid-cols-2">@foreach($cards as $card)<article class="overflow-hidden rounded-3xl bg-white shadow-xl"><div class="relative overflow-hidden bg-gradient-to-br from-slate-950 via-slate-800 to-emerald-700 p-6 text-white"><div class="absolute -right-16 -top-20 h-48 w-48 rounded-full border-[26px] border-white/10"></div><div class="relative"><div class="flex items-center justify-between text-xs tracking-widest text-slate-300"><span>payoneerCARD</span><span>VIRTUAL</span></div><div class="mt-8 flex items-center justify-between"><div class="h-10 w-14 rounded-md bg-amber-300"></div><span class="text-2xl font-black italic">mc</span></div><p class="mt-7 font-mono text-xl tracking-[.16em]">{{ $card->card_number }}</p><div class="mt-6 flex items-end justify-between text-xs text-slate-300"><span>VALID THRU<br><strong class="text-sm text-white">{{ $card->card_expiry }}</strong></span><span>CARDHOLDER<br><strong class="text-sm text-white">{{ $card->card_holder_name }}</strong></span><span class="text-2xl font-black italic text-white">mc</span></div></div></div><div class="p-6"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">{{ $card->card_info_name ?: $card->product?->name }}</p><h2 class="mt-1 text-lg font-black text-slate-900">Card Details</h2></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">Approved</span></div><div class="mt-5 grid grid-cols-2 gap-3 text-sm"><div class="rounded-xl bg-slate-50 p-3"><span class="text-slate-400">CVV</span><strong class="mt-1 block text-slate-900">{{ $card->card_cvv }}</strong></div><div class="rounded-xl bg-slate-50 p-3"><span class="text-slate-400">Order</span><strong class="mt-1 block text-slate-900">#{{ $card->id }}</strong></div></div>@if($card->card_info_note)<div class="mt-4 whitespace-pre-line rounded-xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-900">{{ $card->card_info_note }}</div>@endif</div></article>@endforeach</div>@endif
    </div>
</main>
@endsection
