@extends('layouts.master')

@section('content')
<main class="min-h-screen bg-slate-50 py-12">
    <div class="mx-auto max-w-3xl px-4">
        <a href="{{ url('/') }}#order" class="text-sm font-bold text-emerald-700">← পণ্যের তালিকায় ফিরুন</a>
        <div class="mt-5 rounded-3xl bg-white p-6 shadow-xl sm:p-8">
            <div class="flex flex-col justify-between gap-4 border-b border-slate-100 pb-6 sm:flex-row sm:items-start"><div><p class="text-sm font-black uppercase tracking-wider text-emerald-600">অর্ডার ফর্ম</p><h1 class="mt-2 text-3xl font-black text-slate-950">{{ $product->name }}</h1><p class="mt-2 text-slate-500">{{ $product->description }}</p></div><div class="text-left sm:text-right"><p class="text-sm text-slate-500">পরিশোধযোগ্য</p><p class="mt-1 text-3xl font-black text-slate-950">{{ $product->currency }} {{ number_format((float) $product->price, 2) }}</p></div></div>
            @if ($errors->any())<div class="mt-6 rounded-2xl bg-red-50 p-4 text-sm text-red-700"><ul class="list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <div class="mt-6 rounded-2xl bg-slate-50 p-4 text-sm text-slate-700"><p class="font-bold">Payment করুন এই account-এ</p>@if($settings->bkash_number)<p class="mt-2"><strong>bKash:</strong> {{ $settings->bkash_number }}</p>@endif @if($settings->nagad_number)<p><strong>Nagad:</strong> {{ $settings->nagad_number }}</p>@endif @if($settings->rocket_number)<p><strong>Rocket:</strong> {{ $settings->rocket_number }}</p>@endif @if($settings->bank_name)<p><strong>{{ $settings->bank_name }}:</strong> {{ $settings->bank_account_number }} ({{ $settings->bank_account_name }}){{ $settings->bank_branch ? ' - '.$settings->bank_branch : '' }}</p>@endif @if($settings->payment_instructions)<p class="mt-2 whitespace-pre-line text-slate-500">{{ $settings->payment_instructions }}</p>@endif</div>
            <form class="mt-7 space-y-6" method="POST" action="{{ route('orders.store') }}" enctype="multipart/form-data">@csrf<input type="hidden" name="product_id" value="{{ $product->id }}"><div class="grid gap-5 sm:grid-cols-2"><div><label class="block text-sm font-bold text-slate-700">আপনার নাম *</label><input name="customer_name" value="{{ old('customer_name', auth()->user()->name) }}" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-emerald-200"></div><div><label class="block text-sm font-bold text-slate-700">ইমেইল *</label><input type="email" name="customer_email" value="{{ old('customer_email', auth()->user()->email) }}" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-emerald-200"></div><div><label class="block text-sm font-bold text-slate-700">মোবাইল নম্বর *</label><input name="customer_phone" value="{{ old('customer_phone') }}" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-emerald-200"></div><div><label class="block text-sm font-bold text-slate-700">পেমেন্ট মাধ্যম *</label><select name="payment_method" required class="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none"><option value="">নির্বাচন করুন</option>@foreach(['bKash','Nagad','Rocket','Bank Transfer'] as $method)<option value="{{ $method }}" {{ old('payment_method') === $method ? 'selected' : '' }}>{{ $method }}</option>@endforeach</select></div></div><div><label class="block text-sm font-bold text-slate-700">যে নম্বর/অ্যাকাউন্ট থেকে পেমেন্ট করেছেন *</label><input name="payment_number" value="{{ old('payment_number') }}" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-emerald-200"><p class="mt-1 text-xs text-slate-500">পেমেন্ট করার নম্বর বা ব্যাংক account/reference দিন।</p></div><div><label class="block text-sm font-bold text-slate-700">পেমেন্ট স্লিপ *</label><input type="file" name="payment_slip" accept="image/jpeg,image/png,image/webp,application/pdf" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"><p class="mt-1 text-xs text-slate-500">JPG, PNG, WEBP অথবা PDF, সর্বোচ্চ ৫MB</p></div><div class="rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-amber-800">পেমেন্টের আগে product price মিলিয়ে নিন। Admin যাচাই শেষ না হওয়া পর্যন্ত order status <strong>Pending</strong> থাকবে।</div><button class="w-full rounded-2xl bg-emerald-600 py-4 font-black text-white shadow-lg shadow-emerald-600/20 hover:bg-emerald-700">অর্ডার জমা দিন</button></form>
        </div>
    </div>
</main>
@endsection
