@extends('admin.layout.layout')

@section('content')
<script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
<main class="flex-1 overflow-y-auto bg-gray-50 p-4 md:p-6">
    <div class="mx-auto max-w-5xl">
        <div class="mb-6"><h1 class="text-2xl font-bold text-gray-800">Site Settings</h1><p class="mt-1 text-sm text-gray-500">Manage website identity, support contacts, payment accounts and customer information.</p></div>
        @if(session('success'))<div class="mb-5 rounded-lg bg-green-100 px-4 py-3 text-green-800">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-lg bg-red-100 p-4 text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="POST" action="{{ route('admin.settings.update') }}" class="space-y-6">@csrf @method('PUT')
            <section class="rounded-xl bg-white p-6 shadow"><h2 class="text-lg font-bold text-gray-900">Website & Contact</h2><div class="mt-4 grid gap-5 md:grid-cols-2"><div><label class="block text-sm font-semibold text-gray-700">Site Name *</label><input name="site_name" value="{{ old('site_name', $settings->site_name) }}" required class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Site Email</label><input type="email" name="site_email" value="{{ old('site_email', $settings->site_email) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">WhatsApp Number</label><input name="whatsapp_number" placeholder="8801XXXXXXXXX" value="{{ old('whatsapp_number', $settings->whatsapp_number) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Support Phone</label><input name="support_phone" value="{{ old('support_phone', $settings->support_phone) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div class="md:col-span-2"><label class="block text-sm font-semibold text-gray-700">Support Text</label><textarea name="support_text" rows="3" class="mt-1 w-full rounded border px-3 py-2">{{ old('support_text', $settings->support_text) }}</textarea></div></div></section>
            <section class="rounded-xl bg-white p-6 shadow"><h2 class="text-lg font-bold text-gray-900">Payment Accounts</h2><p class="mt-1 text-sm text-gray-500">These accounts will be shown to customers on the order form.</p><div class="mt-4 grid gap-5 md:grid-cols-3"><div><label class="block text-sm font-semibold text-gray-700">bKash Number</label><input name="bkash_number" value="{{ old('bkash_number', $settings->bkash_number) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Nagad Number</label><input name="nagad_number" value="{{ old('nagad_number', $settings->nagad_number) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Rocket Number</label><input name="rocket_number" value="{{ old('rocket_number', $settings->rocket_number) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Bank Name</label><input name="bank_name" value="{{ old('bank_name', $settings->bank_name) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Account Name</label><input name="bank_account_name" value="{{ old('bank_account_name', $settings->bank_account_name) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Account Number</label><input name="bank_account_number" value="{{ old('bank_account_number', $settings->bank_account_number) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Branch</label><input name="bank_branch" value="{{ old('bank_branch', $settings->bank_branch) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div class="md:col-span-2"><label class="block text-sm font-semibold text-gray-700">Payment Instructions</label><textarea name="payment_instructions" rows="3" class="mt-1 w-full rounded border px-3 py-2">{{ old('payment_instructions', $settings->payment_instructions) }}</textarea></div></div></section>
            <section class="rounded-xl bg-white p-6 shadow"><h2 class="text-lg font-bold text-gray-900">Order & Policies</h2><div class="mt-4 grid gap-5"><div><label class="block text-sm font-semibold text-gray-700">Order Processing Time</label><input name="order_processing_time" value="{{ old('order_processing_time', $settings->order_processing_time) }}" placeholder="৫–১৫ মিনিট" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Privacy Policy</label><textarea id="privacy_policy" name="privacy_policy" rows="8" class="rich-text-editor mt-1 w-full rounded border px-3 py-2">{{ old('privacy_policy', $settings->privacy_policy) }}</textarea></div><div><label class="block text-sm font-semibold text-gray-700">Terms of Service</label><textarea id="terms_of_service" name="terms_of_service" rows="8" class="rich-text-editor mt-1 w-full rounded border px-3 py-2">{{ old('terms_of_service', $settings->terms_of_service) }}</textarea></div><div><label class="block text-sm font-semibold text-gray-700">Refund Policy</label><textarea id="refund_policy" name="refund_policy" rows="8" class="rich-text-editor mt-1 w-full rounded border px-3 py-2">{{ old('refund_policy', $settings->refund_policy) }}</textarea></div></div></section>
            <button class="rounded bg-primary-700 px-6 py-3 font-semibold text-white hover:bg-primary-800">Save Settings</button>
        </form>
    </div>
</main>
@endsection

@push('scripts')
<script>
    document.querySelectorAll('.rich-text-editor').forEach(function (editor) {
        CKEDITOR.replace(editor.id, { height: 220 });
    });
</script>
@endpush
