@extends('admin.layout.layout')

@section('content')
<main class="flex-1 overflow-y-auto bg-gray-50 p-4 md:p-6">
    <div class="mx-auto max-w-4xl rounded-lg bg-white p-6 shadow">
        <div class="mb-6 flex items-center justify-between"><div><p class="text-sm text-gray-500">Order #{{ $order->id }}</p><h1 class="mt-1 text-2xl font-bold text-gray-800">Review Card Order</h1></div><a href="{{ route('admin.order.list') }}" class="text-sm font-semibold text-blue-600">← Back to orders</a></div>
        <div class="mb-6 grid gap-4 rounded-lg bg-gray-50 p-4 text-sm sm:grid-cols-2"><div><span class="text-gray-500">Customer</span><strong class="mt-1 block">{{ $order->customer_name }}</strong><span>{{ $order->customer_email }} · {{ $order->customer_phone }}</span></div><div><span class="text-gray-500">Product</span><strong class="mt-1 block">{{ $order->product?->name ?? 'Product removed' }}</strong><span>{{ $order->product?->currency ?? 'USD' }} {{ number_format((float) $order->amount, 2) }}</span></div><div><span class="text-gray-500">Payment</span><strong class="mt-1 block">{{ $order->payment_method }}</strong><span>{{ $order->payment_number }}</span></div><div>@if($order->payment_slip)<span class="text-gray-500">Payment slip</span><a target="_blank" href="{{ asset('uploads/order-slips/'.$order->payment_slip) }}" class="mt-1 block font-semibold text-blue-600 hover:underline">Open uploaded slip</a>@endif</div></div>
        @if($errors->any())<div class="mb-5 rounded bg-red-100 p-4 text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="POST" action="{{ route('admin.order.update', $order) }}" class="space-y-5">@csrf @method('PUT')
            <div><label class="block font-semibold text-gray-700">Order Status *</label><select name="status" required class="mt-1 w-full rounded border px-3 py-2"><option value="pending" {{ old('status', $order->status) === 'pending' ? 'selected' : '' }}>Pending</option><option value="approved" {{ old('status', $order->status) === 'approved' ? 'selected' : '' }}>Approved</option><option value="rejected" {{ old('status', $order->status) === 'rejected' ? 'selected' : '' }}>Rejected</option></select></div>
            <div class="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><h2 class="font-bold text-emerald-900">Card Information</h2><p class="mt-1 text-sm text-emerald-700">Status Approved করার পর customer এই তথ্য My Card-এ দেখতে পাবে।</p><div class="mt-4 grid gap-4 sm:grid-cols-2"><div><label class="block text-sm font-semibold text-gray-700">Card Info Name</label><input name="card_info_name" value="{{ old('card_info_name', $order->card_info_name) }}" placeholder="Payoneer Premium Card" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Card Holder Name</label><input name="card_holder_name" value="{{ old('card_holder_name', $order->card_holder_name) }}" placeholder="CUSTOMER NAME" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Card Number</label><input name="card_number" value="{{ old('card_number', $order->card_number) }}" placeholder="0000 0000 0000 0000" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">Expiry Date</label><input name="card_expiry" value="{{ old('card_expiry', $order->card_expiry) }}" placeholder="12/30" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="block text-sm font-semibold text-gray-700">CVV</label><input name="card_cvv" value="{{ old('card_cvv', $order->card_cvv) }}" placeholder="123" class="mt-1 w-full rounded border px-3 py-2"></div></div><div class="mt-4"><label class="block text-sm font-semibold text-gray-700">Card Note / Extra Information</label><textarea name="card_info_note" rows="5" placeholder="Card ব্যবহারের নির্দেশনা বা অতিরিক্ত তথ্য লিখুন" class="mt-1 w-full rounded border px-3 py-2">{{ old('card_info_note', $order->card_info_note) }}</textarea></div></div>
            <div><label class="block font-semibold text-gray-700">Admin Note</label><textarea name="admin_note" rows="3" class="mt-1 w-full rounded border px-3 py-2">{{ old('admin_note', $order->admin_note) }}</textarea></div><button class="rounded bg-primary-700 px-6 py-3 font-semibold text-white hover:bg-primary-800">Save Order Update</button>
        </form>
    </div>
</main>
@endsection
