@extends('admin.layout.layout')

@section('content')
<main class="flex-1 overflow-y-auto bg-gray-50 p-4 md:p-6"><div class="mx-auto max-w-7xl">
    <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-wider text-primary-700">Operations</p><h1 class="mt-1 text-2xl font-bold text-gray-800">Card Orders</h1><p class="mt-1 text-sm text-gray-500">Review payments, update status and provide card information.</p></div><div class="rounded-lg bg-white px-4 py-3 text-sm text-gray-600 shadow">Total orders: <strong class="text-gray-900">{{ $orders->total() }}</strong></div></div>
    @if(session('success'))<div class="mb-5 rounded-lg bg-green-100 px-4 py-3 text-green-800">{{ session('success') }}</div>@endif
    <form method="GET" action="{{ route('admin.order.list') }}" class="mb-6 rounded-xl bg-white p-4 shadow-sm"><div class="grid gap-3 md:grid-cols-[minmax(0,1fr)_170px_180px_170px_auto_auto]"><input type="search" name="search" value="{{ request('search') }}" placeholder="Search order, customer, email or payment number" class="rounded-lg border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100"><select name="status" class="rounded-lg border border-gray-200 px-3 py-2.5 text-sm"><option value="">All statuses</option>@foreach(['pending','approved','rejected'] as $status)<option value="{{ $status }}" {{ request('status') === $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>@endforeach</select><select name="product_id" class="rounded-lg border border-gray-200 px-3 py-2.5 text-sm"><option value="">All products</option>@foreach($products as $product)<option value="{{ $product->id }}" {{ (string) request('product_id') === (string) $product->id ? 'selected' : '' }}>{{ $product->name }}</option>@endforeach</select><select name="payment_method" class="rounded-lg border border-gray-200 px-3 py-2.5 text-sm"><option value="">All payment methods</option>@foreach(['bKash','Nagad','Rocket','Bank Transfer'] as $method)<option value="{{ $method }}" {{ request('payment_method') === $method ? 'selected' : '' }}>{{ $method }}</option>@endforeach</select><button class="rounded-lg bg-primary-700 px-5 py-2.5 text-sm font-bold text-white hover:bg-primary-800">Search</button><a href="{{ route('admin.order.list') }}" class="rounded-lg border border-gray-200 px-5 py-2.5 text-center text-sm font-bold text-gray-600 hover:bg-gray-50">Reset</a></div></form>
    <div class="overflow-x-auto rounded-xl bg-white shadow-lg"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-100"><tr><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Order</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Customer</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Product</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Payment</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Status</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Action</th></tr></thead><tbody class="divide-y divide-gray-200">
    @forelse($orders as $order)<tr class="hover:bg-gray-50"><td class="px-5 py-4 text-sm"><strong>#{{ $order->id }}</strong><div class="mt-1 text-xs text-gray-400">{{ $order->created_at->format('d M Y, h:i A') }}</div></td><td class="px-5 py-4 text-sm"><strong>{{ $order->customer_name }}</strong><div class="text-xs text-gray-500">{{ $order->customer_phone }}</div><div class="text-xs text-gray-500">{{ $order->customer_email }}</div></td><td class="px-5 py-4 text-sm text-gray-700">{{ $order->product?->name ?? 'Product removed' }}<div class="text-xs text-gray-500">{{ $order->product?->currency ?? 'USD' }} {{ number_format((float) $order->amount, 2) }}</div></td><td class="px-5 py-4 text-sm text-gray-700">{{ $order->payment_method }}<div class="text-xs text-gray-500">{{ $order->payment_number }}</div>@if($order->payment_slip)<a class="mt-1 inline-block text-xs font-bold text-blue-600 hover:underline" target="_blank" href="{{ asset('uploads/order-slips/'.$order->payment_slip) }}">View slip</a>@endif</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $order->status === 'approved' ? 'bg-green-100 text-green-800' : ($order->status === 'rejected' ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800') }}">{{ ucfirst($order->status) }}</span></td><td class="px-5 py-4"><div class="flex gap-2"><a href="{{ route('admin.order.edit', $order) }}" class="rounded bg-blue-500 px-3 py-1.5 text-sm text-white hover:bg-blue-600">Review</a><form method="POST" action="{{ route('admin.order.destroy', $order) }}">@csrf @method('DELETE')<button onclick="return confirm('Delete this order?')" class="rounded bg-red-500 px-3 py-1.5 text-sm text-white hover:bg-red-600">Delete</button></form></div></td></tr>
    @empty<tr><td colspan="6" class="px-5 py-14 text-center text-sm text-gray-500">No orders matched your filters.</td></tr>@endforelse
    </tbody></table></div><div class="mt-5">{{ $orders->links() }}</div>
</div></main>
@endsection
