@extends('admin.layout.layout')

@section('content')
<main class="flex-1 overflow-y-auto bg-gray-50 p-4 md:p-6"><div class="mx-auto max-w-7xl">
    <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-wider text-primary-700">Catalogue</p><h2 class="mt-1 text-2xl font-bold text-gray-800">Products</h2><p class="mt-1 text-sm text-gray-500">Manage the virtual card products shown on the homepage.</p></div><a href="{{ route('admin.product.create') }}" class="rounded-lg bg-green-600 px-6 py-2.5 font-semibold text-white shadow-md hover:bg-green-700">Add Product</a></div>
    @if(session('success'))<div class="mb-5 rounded-lg bg-green-100 px-4 py-3 text-green-800">{{ session('success') }}</div>@endif
    <form method="GET" action="{{ route('admin.product.list') }}" class="mb-6 rounded-xl bg-white p-4 shadow-sm"><div class="grid gap-3 md:grid-cols-[minmax(0,1fr)_180px_auto_auto]"><input type="search" name="search" value="{{ request('search') }}" placeholder="Search product, description or feature" class="rounded-lg border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100"><select name="status" class="rounded-lg border border-gray-200 px-3 py-2.5 text-sm"><option value="">All statuses</option><option value="active" {{ request('status') === 'active' ? 'selected' : '' }}>Active</option><option value="inactive" {{ request('status') === 'inactive' ? 'selected' : '' }}>Inactive</option></select><button class="rounded-lg bg-primary-700 px-5 py-2.5 text-sm font-bold text-white hover:bg-primary-800">Search</button><a href="{{ route('admin.product.list') }}" class="rounded-lg border border-gray-200 px-5 py-2.5 text-center text-sm font-bold text-gray-600 hover:bg-gray-50">Reset</a></div></form>
    <div class="overflow-x-auto rounded-xl bg-white shadow-lg"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-100"><tr><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">#</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Product</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Price</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Delivery</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Status</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-600">Actions</th></tr></thead><tbody class="divide-y divide-gray-200">
        @forelse($products as $product)<tr class="hover:bg-gray-50"><td class="px-5 py-4 text-sm text-gray-500">{{ $products->firstItem() + $loop->index }}</td><td class="px-5 py-4"><div class="flex items-center gap-3">@if($product->image)<img src="{{ asset('uploads/products/'.$product->image) }}" class="h-10 w-14 rounded object-cover" alt="{{ $product->name }}">@endif<div><div class="font-semibold text-gray-800">{{ $product->name }}</div><div class="text-sm text-gray-500">Order: {{ $product->sort_order }}</div></div></div></td><td class="px-5 py-4 text-sm text-gray-700">{{ $product->currency }} {{ number_format((float) $product->price, 2) }}</td><td class="px-5 py-4 text-sm text-gray-500">{{ $product->delivery_time ?: '—' }}</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $product->status === 'active' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800' }}">{{ ucfirst($product->status) }}</span></td><td class="px-5 py-4"><div class="flex gap-2"><a href="{{ route('admin.product.edit', $product->id) }}" class="rounded bg-blue-500 px-3 py-1.5 text-sm text-white hover:bg-blue-600">Edit</a><form method="POST" action="{{ route('admin.product.destroy', $product->id) }}">@csrf @method('DELETE')<button type="submit" onclick="return confirm('Delete this product?')" class="rounded bg-red-500 px-3 py-1.5 text-sm text-white hover:bg-red-600">Delete</button></form></div></td></tr>
        @empty<tr><td colspan="6" class="px-5 py-14 text-center text-sm text-gray-500">No products matched your filters.</td></tr>@endforelse
    </tbody></table></div><div class="mt-5">{{ $products->links() }}</div>
</div></main>
@endsection
